### ISSUE TITLE
Múltiplos toasts quando mais de uma receita é encontrada

### ISSUE THREAD

**Issue by danielpsf** [gabrielrms-Inatel/ProjetoFaitec#1]
Quando mais de uma receita é encontrada, múltiplos toasts aparecem na tela:

![screenshot_1](https://cloud.githubusercontent.com/assets/3307367/10246115/b3c71cac-68e4-11e5-9114-aa34466a6ee4.png)

**Comment by danielpsf** [comment]
Como o toast está dentro do `for` ele sempre executa isso mais de uma vez, para cada receita que ele encontra.

https://github.com/gabrielrms-Inatel/ProjetoFaitec/blob/master/www/js/index.js#L63

**Comment by gabriel-mars** [comment]
Please verify if this bug still happens.

**Comment by danielpsf** [comment]
It's fixed now. Thanks.

**Comment by gabriel-mars** [comment]
This bug should be fixed with the implementation of validation

**Comment by danielpsf** [comment]
Now it's fixed!
