### ISSUE TITLE
Toast de "Receitas Encontradas" quando nenhuma receita foi encontrada

### ISSUE THREAD

**Issue by rodrigofaria** [gabrielrms-Inatel/ProjetoFaitec#2]
-> Selecione Leite
-> Clique "Buscar Receitas"
-> Toast irá aparecer dizendo "Receita(s) Encontrada(s)" mesmo não tendo encontrado nenhuma receita.

**Comment by gabrielrms-Inatel** [comment]
close #2

**Comment by gabriel-mars** [comment]
Corrigido!
