### ISSUE TITLE
Página inicial deveria ser um splash

### ISSUE THREAD

**Issue by danielpsf** [gabrielrms-Inatel/ProjetoFaitec#3]
Ao entrar na aplicação, é exibida uma página inicial (veja abaixo), que deveria ser um splash ao invés de uma tela e um botão:

![image](https://cloud.githubusercontent.com/assets/3307367/10315868/233a6c14-6c33-11e5-848b-4ee81b2447e1.png)

How to configure splash screen:
![image](https://cloud.githubusercontent.com/assets/3307367/10315936/74c9c444-6c33-11e5-901f-b8a9065eed95.png)

ou:
http://docs.phonegap.com/en/2.2.0/cordova_splashscreen_splashscreen.md.html

**Comment by gabriel-mars** [comment]
Eu estava justamente procurando como fazer isso.

**Comment by gabriel-mars** [comment]
Fixed
