### ISSUE TITLE
Página "About" ("Sobre") não deveria ser exibida antes da funcionalidade

### ISSUE THREAD

**Issue by danielpsf** [gabrielrms-Inatel/ProjetoFaitec#4]
Uma das principais coisas no desenvolvimento mobile é ser usável, ou seja, rápido e prático de se usar. Colocar a página de sobre (about) como a primeira tela não irá ajudar a ganhar a atenção dos usuários para seu aplicativo.

![image](https://cloud.githubusercontent.com/assets/3307367/10316001/d46b4274-6c33-11e5-9fc7-f9b884fe06eb.png)

Esta tela deveria estar dentro de um menu, com a opção "Sobre"

**Comment by gabriel-mars** [comment]
Obrigado pela dica. Vou corrigir este bug.

**Comment by gabriel-mars** [comment]
Corrigido!
