### ISSUE TITLE
As opções "Apresentação" e "Próxima página" não devem ser exibidas juntamente com a receita

### ISSUE THREAD

**Issue by danielpsf** [gabrielrms-Inatel/ProjetoFaitec#5]
Para que a usabilidade do seu aplicativo melhore, sugiro a criação de um menu com as opções:
- Procurar receitas
  - Atual terceira página
- Créditos
  - Atual "Próxima página"
- Sobre o aplicativo
  - Atual segunda página

![image](https://cloud.githubusercontent.com/assets/3307367/10316186/7381ff7e-6c34-11e5-87ab-56b15d8befc5.png)

**Comment by gabriel-mars** [comment]
This feature was implemented
